version: '3.9'

services:
  frontend:
    build:
      context: ./ecommerce_frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ./ecommerce_frontend:/app
      - /app/node_modules
    working_dir: /app
    command: ["npm", "start"]

  backend:
    build:
      context: ./ecommerce_backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./ecommerce_backend:/app
    environment:
      - DJANGO_SECRET_KEY=django-insecure-8(jtq*yjete+%@t%u9t1@a=hosfs#!!d88y2w3*ye5mpzv4=d_
      - DJANGO_DEBUG=True
      - DB_NAME=ecommerce_db
      - DB_USER=postgres
      - DB_PASSWORD=root123
      - DB_HOST=db
      - DB_PORT=5432
    depends_on:
      - db

  db:
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root123
      POSTGRES_DB: ecommerce_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
