# Generated by Django 5.1.4 on 2025-01-14 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_product_search_vector'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='search_vector',
        ),
    ]
